hms/hms/urls.py
from django.contrib import admin

from accounts import views
from django.conf import settings  # new
from django.urls import path, include  # new
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('accounts.urls')),
    path('', views.landing, name='landing'),

]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hms/posts/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('addpost/', views.post_new, name='addpost'),
    path('notices', views.PostList.as_view(), name='notices'),
    path('noticesstud', views.PostListStud.as_view(), name='noticesstud'),
    path('delete/<str:tag>', views.post_delete, name='delete'),
]

hms/posts/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.title

hms/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content',)

hms/posts/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import generic

from .forms import PostForm
from .models import Post


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            post.save()
            return redirect('notices')
        else:
            return render(request, 'posts/addpost.html', {'form': form})
            print('error')
    else:
        form = PostForm()
        return render(request, 'posts/addpost.html', {'form': form})
        # return redirect('addpost')


def post_delete(request, tag):
    obj = Post.objects.get(title=tag)
    obj.delete()
    return redirect('notices')


class PostList(generic.ListView):
    queryset = Post.objects.all().order_by('-created_on')
    template_name = 'posts/allpost.html'


class PostListStud(generic.ListView):
    queryset = Post.objects.all().order_by('-created_on')
    template_name = 'posts/allpost_student.html'

hms/posts/templates/posts/addpost.html
{% extends 'accounts/base.html' %}
{% block side %}

<a class="nav-link nav-social" href="{% url 'student' %}">Room Management</a>
<a class="nav-link nav-social" href="{% url 'addpost' %}">New Notice</a>
<a class="nav-link nav-social" href="{% url 'logout' %}">Logout</a>


{% endblock %}

{% block content %}
<!--<div class="row text-left">-->
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">

        <form method="POST" class="post-form text-center border border-light p-5"
              onsubmit="send.disabled = true; return true;" action="{% url 'addpost' %}">
            {% csrf_token %}
            <h3>Add a New Notice</h3>
            <hr>

            <input type="text" id="title" name="title" class="form-control mb-4" placeholder="Enter Title">
            <textarea name="content" class="form-control mb-4" cols="40" rows="10"
                      id="id_content" placeholder="Enter Content"></textarea>
            <button type="submit" name="send" class="btn btn-info my-4 btn-block">Save</button>
        </form>
    </div>

    <div class="col-sm-3">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <small>({{ field.label }})</small>
            <small>{{ error|escape }}</small>
        </div>
        {% endfor %}
        {% endfor %}

        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <small>({{ field.label }})</small>
            <small>{{ error|escape }}</small>
        </div>
        {% endfor %}
        {% endif %}
    </div>

</div>

{% endblock %}

hms/posts/templates/posts/allpost.html
{% extends 'accounts/base.html' %}
{% block side %}

<a class="nav-link nav-social" href="{% url 'student' %}">Room Management</a>
<a class="nav-link nav-social" href="{% url 'addpost' %}">New Notice</a>
<a class="nav-link nav-social" href="{% url 'logout' %}">Logout</a>


{% endblock %}

{% block content %}
<div class="row text-left">
    <!--<div class="row" style="padding-top:10%">-->
    {% for post in post_list %}
    <div class="col-sm-3"></div>
    <div class="col-sm-6" style="padding-bottom: 5rem;">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-dark">{{ post.title }}</h4>
                <hr>
                <p class="card-text text-dark">{{ post.content }} <br>
                </p>
                <hr>
                <p class="card-text text-dark">
                    Announced on: {{ post.created_on }}

                </p>
                <a class="text-danger" style="cursor:pointer;" onclick="confirmDelete('{% url 'delete' post.title %}')">Delete
                    Post</a>
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>
    {% empty %}
    <div class="col-sm-12">
        <div class="bgimg w3-display-container w3-animate-opacity w3-text-white">
            <div class="w3-display-middle">
                <h1 class="w3-jumbo w3-animate-top text-center">No Notices</h1>
                <hr class="w3-border-grey" style="margin:auto;width:60%">
                <p class="w3-large w3-center" style="text-align: center;">
                    <a href="{% url 'student' %}">Go back</a>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
    <!--</div>-->
</div>

<script>

    function confirmDelete(url){
        if(confirm('Are You sure to delete this?')){
            location.href = url;
        }
    }


</script>

{% endblock %}

hms/posts/templates/posts/allpost_student.html
{% extends 'accounts/base.html' %}
{% block side %}

<!--<a class="nav-link nav-social">Welcome {{ name }}</a>-->
<!--<a class="nav-link nav-social" href="{% url 'history' %}">Fees History</a>-->

<a class="nav-link nav-social" href="{% url 'student' %}">Go Back</a>
<a class="nav-link nav-social" href="{% url 'logout' %}">Logout</a>

{% endblock %}

{% block content %}
<div class="row text-left">
    <!--<div class="row" style="padding-top:10%">-->
    {% for post in post_list %}
    <div class="col-sm-3"></div>
    <div class="col-sm-6" style="padding-bottom: 5rem;">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-dark">{{ post.title }}</h4>
                <hr>
                <p class="card-text text-dark">{{ post.content }} <br>
                </p>
                <hr>
                <p class="card-text text-dark">
                    Announced on: {{ post.created_on }}

                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>
    {% empty %}
    <div class="col-sm-12">
        <div class="bgimg w3-display-container w3-animate-opacity w3-text-white">
            <div class="w3-display-middle">
                <h1 class="w3-jumbo w3-animate-top text-center">No Notices</h1>
                <hr class="w3-border-grey" style="margin:auto;width:60%">
                <p class="w3-large w3-center" style="text-align: center;">
                    <a href="{% url 'student' %}">Go back</a>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
    <!--</div>-->
</div>
{% endblock %}

hms/posts/templates/posts/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HMS</title>
    <meta name="description" content="A Sample Hostel Management Project done in Django"/>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link href="{%static 'bootstrap/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{%static 'bootstrap/styles/main.css' %}" rel="stylesheet">
</head>

<header>
  <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: rgba(0,0,0,.6);">
    <div class="container">
      <a class="navbar-brand" href="{% url 'student' %}"><strong>HMS</strong></a>
<!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"-->
<!--        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
         <ul class="nav  justify-content-end">
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">Home</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">Link</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">Profile</a>-->
<!--          </li>-->
            {% block side %}

             {% endblock %}
        </ul>

    </div>
  </nav>
</header>
<body id="top">

<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="masthead clearfix">
<!--                <div class="inner">-->
<!--                    <h3 class="masthead-brand">HMS</h3>-->
<!--                    <nav class="nav nav-masthead">-->
<!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>&ndash;&gt;-->
<!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>&ndash;&gt;-->
<!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>&ndash;&gt;-->
<!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>&ndash;&gt;-->

<!--                    </nav>-->
<!--                </div>-->
            </div>
            <br>
            {% block content %}


            {% endblock %}
            <!--            <div class="mastfoot">-->
            <!--                <div class="inner">-->
            <!--                    <p>&copy; 2019 HMS </p>-->
            <!--                </div>-->
            <!--            </div>-->


        </div>
    </div>
</div>
<footer class="footer" style="background-color: rgba(0,0,0,.6);">
    <span class="text-light">&copy; 2019 HMS </span>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
<script src="{%static 'bootstrap/scripts/main.js' %}"></script>
</body>
</html>