hms/accounts/urls.py
import debug_toolbar
from django.conf.urls import url
from django.urls import path, include
from . import views

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

    path('register/', views.register, name='register'),
    path('testing/', views.testing, name='testing'),
    path('student/', views.student_details_view, name='student'),
    path('rooms/', views.room_all_view, name='rooms'),
    # path('roomselect/', views.room_select, name='roomselect')
    # path('roomselect/<str:tag>', views.room_select, name='roomselect'),
    path('roomselect/<str:tag>', views.room_select_new, name='roomselect'),
    path('roomstud/<str:tag>', views.room_details, name='roomdetails'),
    path('warden', views.room_all_view_warden, name='wardenhome'),
    path('addroom/', views.addroom, name='addroom'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('update/', views.update, name='update'),
    path('changeroom/', views.room_change_view, name='changeroom'),
    path('roomchangeap/<str:tag>', views.room_change, name='roomchangeap'),
    path('applist/', views.approve_all_view_warden, name='applist'),
    path('applistnew/', views.new_approve_all_view_warden, name='applistnew'),
    path('appconfirm/<str:tag>', views.approve_confirm, name='appconfirm'),
    path('roomcheck', views.room_change_check, name='roomcheck'),
    path('reject/<str:tag>', views.approve_reject, name='reject'),
    path('history', views.fee_student_history, name='history'),
    path('topay', views.fee_instructions, name='topay'),
    path('feeregister/<str:tag>', views.fee_register, name='feeregister'),
    path('feesall', views.fee_approval_list, name='feesall'),
    path('feeconfirm/<str:tag>', views.fees_approve_confirm, name='feeconfirm'),
    path('feereject/<str:tag>', views.fees_approve_reject, name='feereject'),
    path('studsall', views.all_student, name='studsall'),
    path('studetail/<str:tag>', views.student_profile_admin, name='studetail'),
    path('rejectnew/<str:tag>', views.reject_form, name='rejectnew'),
    path('appconfirmnew/<str:tag>', views.approve_confirm_new, name='appconfirmnew'),
    path('rejectfee/<str:tag>', views.reject_form, name='rejectfee'),
    path('feestatus', views.fee_status, name='feestatus'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

hms/hms/urls.py
from django.contrib import admin

from accounts import views
from django.conf import settings  # new
from django.urls import path, include  # new
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('accounts.urls')),
    path('', views.landing, name='landing'),

]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hms/accounts/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.core.exceptions import PermissionDenied


# Create your models here.

class Room(models.Model):
    no = models.CharField(max_length=5, default=None, unique=True)
    cover = models.ImageField(upload_to='images/')
    room_choice = [('S', 'Single Room'), ('D', 'Double Room'), ('T', 'Triple Room')]
    room_type = models.CharField(choices=room_choice, max_length=1, default=None)
    vacant = models.BooleanField(default=False)
    capacity = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    present = models.PositiveIntegerField(validators=[MaxValueValidator(4)], default=0, blank=True, null=True)

    def __str__(self):
        return self.no


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False)
    location = models.CharField(max_length=10)
    age = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(99)])
    dob = models.DateField(
        max_length=10,
        help_text="format : YYYY-MM-DD",
        null=True, blank=True
    )
    gender_choices = [('M', 'Male'), ('F', 'Female')]
    gender = models.CharField(
        choices=gender_choices,
        max_length=1,
        default=None,
        null=True
    )
    course_choices = [('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE')]
    course = models.CharField(
        choices=course_choices,
        max_length=3,
        default=None,
        null=True
    )
    room_allotted = models.BooleanField(default=False)
    fees_paid = models.BooleanField(default=False)

    def delete(self, *args, **kwargs):
        self.user.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __str__(self):
        return self.user.username


class Approval(models.Model):
    old_room = models.ForeignKey(Room, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False,
                                 related_name='old')
    new_room = models.ForeignKey(Room, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False,
                                 related_name='new')
    requester = models.ForeignKey(UserProfile, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.requester.user.username


class Fees(models.Model):
    student = models.ForeignKey(UserProfile, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False)
    date_paid = models.DateField(auto_now=True)
    amount = models.PositiveIntegerField(validators=[MinValueValidator(9000), MaxValueValidator(15000)])
    is_approved = models.BooleanField(default=False)


class NewRegistration(models.Model):
    requester = models.ForeignKey(UserProfile, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False)
    new_room = models.ForeignKey(Room, on_delete=models.DO_NOTHING, blank=True, null=True, unique=False,
                                 related_name='newroom')


@receiver(pre_delete, sender=User)
def delete_user(sender, instance, **kwargs):
    if instance.is_superuser:
        raise PermissionDenied

hms/accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .tokens import account_activation_token
from .models import UserProfile, Room, Approval, Fees, NewRegistration
# Create your views here.
from .forms import UserProfileForm, ExtendedUserCreationForm, RoomCreationForm, UserUpdateForm, UserProfileUpdateForm, \
    RejectForm
from django.core.mail import send_mail, EmailMessage
from django.conf import settings


def register(request):
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)

            profile.user = user

            profile.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your HMS account.'
            message = render_to_string('registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'registration/email_sent.html')
            # username = form.cleaned_data.get('username')
            # password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=password)
            # login(request, user)
            # return redirect('student')

        else:
            context = {'form': form, 'profile_form': profile_form}
            return render(request, 'accounts/register.html', context)

    else:
        form = ExtendedUserCreationForm()
        profile_form = UserProfileForm()
        context = {'form': form, 'profile_form': profile_form}
        return render(request, 'accounts/register.html', context)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, 'registration/email_confirm.html')
    else:
        return HttpResponse('Activation link is invalid!')


def testing(request):
    return render(request, 'accounts/testing.html')


@login_required()
def student_details_view(request):
    current_user = request.user
    print(current_user)

    if request.user.groups.filter(name__in=['warden']).exists():
        return redirect('wardenhome')

    elif request.user.is_superuser:
        return render(request, 'accounts/testing2.html')

    else:
        obj = UserProfile.objects.select_related('user').get(user=current_user)
        print(obj.user.first_name)
        print(obj.user.last_name)

        try:
            context = {'name': obj.user.first_name, 'location': obj.location, 'age': obj.age,
                       'gender': obj.gender, 'room': obj.room.no, 'email': obj.user.email,
                       'course': obj.course, 'fees': obj.fees_paid}
        except:
            context = {'name': obj.user.first_name, 'location': obj.location, 'age': obj.age,
                       'gender': obj.gender, 'room': 'Not Assigned', 'email': obj.user.email,
                       'course': obj.course, 'fees': obj.fees_paid}
            if request.user.is_authenticated and request.user.is_active:
                request.session['userred'] = True

        # context = {'name': obj.user.first_name, 'location': obj.location, 'age': obj.age,
        #            'gender': obj.gender, 'room': obj.room.no}

        return render(request, 'accounts/detail_view.html', context)


@login_required()
def room_all_view(request):
    if 'userred' in request.session:
        try:
            s = NewRegistration.objects.get(requester__user__username=request.user)
            print(s, 'hello')
            return render(request, 'accounts/room_notallowed.html')
        except:
            request.session['userred1'] = True
            rooms = Room.objects.all()
            roomdata = []
            for x in rooms:
                remains = x.capacity - x.present
                type = x.room_type
                if type == 'S':
                    amount = 15000
                elif type == 'D':
                    amount = 12000
                else:
                    amount = 9000
                y = {'no': x.no, 'type': x.room_type, 'present': x.present, 'remains': remains, 'cover': x.cover,
                     'fees': amount}
                roomdata.append(y)
                print('hello', x.cover)
            context = {'roomdata': roomdata}
            return render(request, 'accounts/room_all.html', context)

    else:
        return render(request, 'accounts/testing.html')


@login_required()
def room_change_view(request):
    # request.session['userred1'] = True
    rooms = Room.objects.all()
    obj = UserProfile.objects.get(user=request.user)
    roomdata = []
    for x in rooms:
        if x != obj.room:
            remains = x.capacity - x.present
            type = x.room_type
            if type == 'S':
                amount = 15000
            elif type == 'D':
                amount = 12000
            else:
                amount = 9000
            y = {'no': x.no, 'type': x.room_type, 'present': x.present, 'remains': remains, 'cover': x.cover,
                 'fees': amount}
            roomdata.append(y)

    context = {'roomdata': roomdata}
    return render(request, 'accounts/change_allrooms.html', context)


@login_required()
def room_change_check(request):
    current_user = request.user
    try:
        app = Approval.objects.get(requester__user__username=current_user)
        print(app)
        return render(request, 'accounts/room_notallowed.html')
    except:
        return room_change_view(request)


@login_required()
def room_all_view_warden(request):
    if request.user.groups.filter(name__in=['warden']).exists():
        rooms = Room.objects.all()

        new_room = NewRegistration.objects.all()
        new_room_count = len(new_room)

        fee = Fees.objects.filter(is_approved=False)
        fee_count = len(fee)

        appr = Approval.objects.all()
        appr_count = len(appr)

        roomdata = []
        for x in rooms:
            remains = x.capacity - x.present
            y = {'no': x.no, 'type': x.room_type, 'present': x.present, 'remains': remains, 'cover': x.cover}
            roomdata.append(y)
            print(x.cover)
        context = {'roomdata': roomdata, 'newroom': new_room_count, 'feen': fee_count, 'appr': appr_count}
        return render(request, 'accounts/room_all_warden.html', context)

    else:
        return render(request, 'accounts/testing.html')


@login_required()
def approve_all_view_warden(request):
    if request.user.groups.filter(name__in=['warden']).exists():
        app = Approval.objects.all()
        appdata = []
        for x in app:
            if not x.is_approved:
                y = {'old': x.old_room.no, 'new': x.new_room.no, 'user': x.requester.user.first_name,
                     'course': x.requester.course, 'username': x.requester, 'userl': x.requester.user.last_name}
                appdata.append(y)
                print(x)
        context = {'appdata': appdata}
        return render(request, 'accounts/approve_list.html', context)

    else:
        return render(request, 'accounts/testing.html')


@login_required()
def new_approve_all_view_warden(request):
    if request.user.groups.filter(name__in=['warden']).exists():
        app = NewRegistration.objects.all()
        appdata = []
        for x in app:
            y = {'new': x.new_room.no, 'user': x.requester.user.first_name, 'userl': x.requester.user.last_name,
                 'course': x.requester.course, 'username': x.requester}
            appdata.append(y)
            print(x)
        context = {'appdata': appdata}
        return render(request, 'accounts/approve_list_new.html', context)

    else:
        return render(request, 'accounts/testing.html')


def reject_form(request, tag):
    if request.user.groups.filter(name__in=['warden']).exists():
        if request.method == 'POST':
            form = RejectForm(request.POST)

            if form.is_valid():
                # msg = request.POST['message']
                msg = request.POST.get('message')
                print(msg)
                app = NewRegistration.objects.filter(requester__user__username=tag).first()
                user = UserProfile.objects.get(user__username=tag)
                subject = 'Your request has been rejected'
                message = 'Your new room selection has been rejected by the warden.' \
                          'Reason: '
                message = message + msg
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [user.user.email]
                send_mail(subject, message, email_from, recipient_list)
                app.delete()

hms/accounts/templates/accounts/add_room.html
{% extends 'accounts/base.html' %}
{% block side %}
<!--<a class="nav-link nav-social">Welcome Warden</a><br>-->
<!--<a class="nav-link nav-social" href="{% url 'update' %}">Update Profile</a>-->
<a class="nav-link nav-social" href="{% url 'notices' %}">Notice Board</a>
<a class="nav-link nav-social" href="{% url 'applistnew' %}">New Approval</a>
<a class="nav-link nav-social" href="{% url 'applist' %}">Room Approval</a>
<a class="nav-link nav-social" href="{% url 'feesall' %}">Fees Approval</a>
<a class="nav-link nav-social" href="{% url 'history' %}">Fees History</a>
<a class="nav-link nav-social" href="{% url 'studsall' %}">All Students</a>
<a class="nav-link nav-social" href="{% url 'addroom' %}">Add a room</a>
<a class="nav-link nav-social" href="{% url 'logout' %}">Logout</a>


{% endblock %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
    $(document).ready(function() {
console.log('hello23');
    $(".room_type").change(function() {
    console.log('hello');
    if ( $(".room_type").val() == "S" )
    {
        console.log('in if');
        $(".room_capacity").val('1');
    }
    if ( $(".room_type").val() == "D" )
    {
        console.log('in if');
        $(".room_capacity").val('2');
    }
    if ( $(".room_type").val() == "T" )
    {
        console.log('in if');
        $(".room_capacity").val('3');
    }

});



});

</script>
<div class="row">
    <div class="col-sm-4">

    </div>
    <div class="col-sm-4">
        <!-- Default form register -->

        <form method="POST" class="text-center border border-light p-5" action="{% url 'addroom' %}"
              onsubmit="send.disabled = true; return true;" enctype="multipart/form-data">
            {% csrf_token %}

            <p class="h4 mb-4">Add New Room</p>

            <!-- Username -->
            <input type="text" id="no" name="no" class="form-control mb-4" placeholder="Room Number">


            <select class="form-control mb-4 room_type" name="room_type">
                <option value="S">Single Room</option>
                <option value="D">Double Room</option>
                <option value="T">Triple Room</option>

            </select>

            <input type="text" id="capacity" name="capacity" value="1" required=""
                   class="form-control mb-4 room_capacity" placeholder="Capacity" readonly>

            <!--            <small class="text-muted">We'll never share your email with anyone else.</small>-->
            <div class="col-xs-10">
                <small class="text-dark">Upload Photo of the Room</small>

                <input type="file" name="cover" class="form-control mb-4" accept="image/*" required="" id="id_cover">
            </div>

            <button name="send" class="btn btn-info my-4 btn-block" type="submit">Add Room</button>

        </form>
        <!-- Default form register -->
    </div>
    <div class="col-sm-3">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <small>({{ field.label }})</small>
            <small>{{ error|escape }}</small>
        </div>
        {% endfor %}
        {% endfor %}

        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <small>({{ field.label }})</small>
            <small>{{ error|escape }}</small>
        </div>
        {% endfor %}
        {% endif %}
    </div>

</div>

<!--<div class="bgimg w3-display-container w3-animate-opacity w3-text-white">-->
<!--    <div class="w3-display-topleft w3-padding-large w3-xlarge">-->
<!--        HMS-->
<!--    </div>-->
<!--    <div style="padding-top: 50px; padding-left: 20px;"></div>-->
<!--    <div style="margin: auto;">-->
<!--        <form method="POST" action="{% url 'addroom' %}" onsubmit="myButton.disabled = true; return true;"-->
<!--              onclick="this.disabled = true;" enctype="multipart/form-data">-->
<!--            {% csrf_token %}-->
<!--            <table border="1">-->
<!--                {{ form.as_table }}-->


<!--            </table>-->
<!--            <input id="myButton" type="submit" value="Add Room">-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->
{% endblock %}


<!--<form method="POST" action="{% url 'addroom' %}" onsubmit="myButton.disabled = true; return true;" onclick="this.disabled = true;">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->

<!--    <input id="myButton" type="submit" value="Create Room">-->
<!--</form>-->

hms/accounts/templates/accounts/approve_list.html
{% extends 'accounts/base.html' %}
{% block side %}
<!--<a class="nav-link nav-social">Welcome Warden</a><br>-->
<!--<a class="nav-link nav-social" href="{% url 'update' %}">Update Profile</a>-->
<a class="nav-link nav-social" href="{% url 'notices' %}">Notice Board</a>
<a class="nav-link nav-social" href="{% url 'applistnew' %}">New Approval</a>
<a class="nav-link nav-social" href="{% url 'applist' %}">Room Approval</a>
<a class="nav-link nav-social" href="{% url 'feesall' %}">Fees Approval</a>
<a class="nav-link nav-social" href="{% url 'history' %}">Fees History</a>
<a class="nav-link nav-social" href="{% url 'studsall' %}">All Students</a>
<a class="nav-link nav-social" href="{% url 'addroom' %}">Add a room</a>
<a class="nav-link nav-social" href="{% url 'logout' %}">Logout</a>


{% endblock %}


{% block content %}


<style>
    #popup{
        position: fixed;
        left: 40%;
        top: 40%;
        height: 130px;
        width: 300px;
        display: none;
        z-index: 100;
        padding: 20px;
        background-color: #fff;
        color: #000;
    }

</style>

<div class="confirmPopup" id="popup">
    <div class="row">
        <div class="col-sm-12" style="margin-bottom: 20px;">
            Are you sure?
        </div>
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-6">
                    <button id="yes" class="btn btn-outline-success" onclick="confirmed()">Yes</button>
                </div>
                <div class="col-sm-6">
                    <button id="no" class="btn btn-outline-danger" onclick="abort()">No</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" style="padding-top:10%;">
    {% for y in appdata %}
    <div class="col-sm-4" style="padding-bottom: 5rem;">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                <h5 class="card-title text-dark">Requested by: {{y.user}} {{y.userl}}</h5>
                <p class="card-title text-dark">Course: {{y.course}}</p>
                <p class="card-title text-dark">({{y.username}})</p>

            </div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-dark">New Room: {{y.new}}</h6>
                <h6 class="card-subtitle mb-2 text-dark">Old Room: {{y.old}}</h6>
                <div class="row">
                    <div class="col-sm-6">
                        <form method="POST" id="{{y.username}}" action="{% url 'appconfirm' y.username %}"
                              onsubmit="approve(event,{{y.username}})">
                            {% csrf_token %}


                            <button name="send" class="btn btn-outline-success bs" type="submit">Approve</button>

                        </form>
                    </div>
                    <div class="col-sm-6">
                        <form action="{% url 'reject' y.username %}"
                              onsubmit="send.disabled = true; return true;">
                            {% csrf_token %}


                            <button name="send" type="submit" class="btn btn-outline-danger bs">Reject</button>

                        </form>
                    </div>

                </div>
            </div>
        </div>

    </div>

    {% empty %}
    <div class="col-sm-12" style="padding-bottom: 5rem;">

        <div class="bgimg w3-display-container w3-animate-opacity w3-text-white">

            <div class="w3-display-middle">
                <h1 class="w3-jumbo w3-animate-top">No Pending Requests!</h1>
                <hr class="w3-border-grey" style="margin:auto;width:60%">
                <p class="w3-large w3-center" style="text-align: center;">
                    <!--         <h1>You have already given a change request</h1>-->

                    <!--                <h3>No inmates here</h3>-->
                    <a href="{% url 'student' %}">Go back</a>
                </p>


            </div>

        </div>
    </div>

    {% endfor %}
</div>
<script>

        var target;
        function approve(event,id){
        console.log('something');
        event.preventDefault();
        target = event.target;
        $('#popup').show();
        console.log($('#popup'));
        console.log('something');
        var btns = document.getElementsByClassName('bs');
            console.log(btns);
            for(let i=0; i<btns.length; i++){
                btns[i].disabled = true;
            }
        }

        function confirmed(){
            target.submit();
            var btns = document.getElementsByClassName('btn');
            console.log(btns);
            for(let i=0; i<btns.length; i++){
                btns[i].disabled = true;
            }
        }

        function abort(){
            $('#popup').hide();
            var btns = document.getElementsByClassName('bs');
            for(let i=0; i<btns.length; i++){
                btns[i].disabled = false;
            }
        }


</script>
{% endblock %}

hms/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HMS</title>
    <meta name="description" content="A Sample Hostel Management Project done in Django"/>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link href="{%static 'bootstrap/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{%static 'bootstrap/styles/main.css' %}" rel="stylesheet">
</head>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: rgba(0,0,0,.6);">
        <div class="container">
            <a class="navbar-brand" href="{% url 'student' %}"><strong>HMS</strong></a>
            <!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"-->
            <!--        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
            <!--        <span class="navbar-toggler-icon"></span>-->
            <!--      </button>-->
            <ul class="nav  justify-content-end">
                <!--          <li class="nav-item">-->
                <!--            <a class="nav-link" href="#">Home</a>-->
                <!--          </li>-->
                <!--          <li class="nav-item">-->
                <!--            <a class="nav-link" href="#">Link</a>-->
                <!--          </li>-->
                <!--          <li class="nav-item">-->
                <!--            <a class="nav-link" href="#">Profile</a>-->
                <!--          </li>-->
                {% block side %}

                {% endblock %}
            </ul>

        </div>
    </nav>
</header>
<body id="top">

<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="masthead clearfix">
                <!--                <div class="inner">-->
                <!--                    <h3 class="masthead-brand">HMS</h3>-->
                <!--                    <nav class="nav nav-masthead">-->
                <!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>&ndash;&gt;-->
                <!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>&ndash;&gt;-->
                <!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>&ndash;&gt;-->
                <!--                        &lt;!&ndash;            <a class="nav-link nav-social" href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>&ndash;&gt;-->

                <!--                    </nav>-->
                <!--                </div>-->
            </div>
            <br>
            {% block content %}


            {% endblock %}

            <!--            <div class="mastfoot">-->
            <!--                <div class="inner">-->
            <!--                    <p>&copy; 2019 HMS </p>-->
            <!--                </div>-->
            <!--            </div>-->


        </div>
    </div>
</div>
<footer class="footer" style="background-color: rgba(0,0,0,.6);">
    <span class="text-light">&copy; 2019 HMS </span>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
<script src="{%static 'bootstrap/scripts/main.js' %}"></script>
</body>
</html>

hms/accounts/templates/accounts/no_fees.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="bgimg w3-display-container w3-animate-opacity w3-text-white">

    <div class="w3-display-middle">
        <h1 class="w3-jumbo w3-animate-top">Nothing Here!</h1>
        <hr class="w3-border-grey" style="margin:auto;width:60%">
        <p class="w3-large w3-center" style="text-align: center;">
        <h3>Have You given a Fee Request?</h3>
        <h4>Once a request is added, you can check the status here</h4>
        <h4>If you cant find a previous request, it has been rejected by the warden.</h4>
        <a href="{% url 'student' %}">Go back to Student</a>
        </p>


    </div>

</div>

<!--<h1>Selected Room is {{ room }}</h1>-->
<!--<a href="{% url 'student' %}">student</a>-->
{% endblock %}

hms/accounts/templates/accounts/testing2.html
<h1>Admin login detected</h1>
<a href="{% url 'logout' %}">Logout</a>